export const STORAGE_KEY = "virtualTrainerDeterministicV2";

export const sessionTypeLabels = {
  mesa: "Mesa",
  mesa_sparring: "Mesa / sparring",
  mesa_tecnica: "Mesa tecnica",
  specific_aw: "Especifico AW",
  multiarticular: "Multiarticular",
  multiarticular_fuerza: "Multiarticular fuerza",
  recovery: "Recuperacion",
  recovery_tissue: "Recuperacion / tejido",
};

export const exerciseCategoryLabels = {
  specific_aw: "Especifico AW",
  multiarticular: "Multiarticular",
  tissue: "Tejido / tolerancia",
  accessory: "Accesorio",
};

export const exercisePatternOptions = [
  "rising",
  "cupping",
  "back_pressure",
  "side_pressure",
  "pronation",
  "supination",
  "drag",
  "high_hook",
  "deep_hook",
  "containment",
  "finish",
  "squat",
  "hinge",
  "horizontal_push",
  "vertical_push",
  "horizontal_pull",
  "vertical_pull",
  "unilateral_leg",
  "trunk_bracing",
  "antirotation",
  "flexor_pronator_isometric",
  "extensor_balance",
  "wrist_control",
  "tendon_tolerance",
];

export const exerciseSideOptions = [
  { value: "right", label: "Derecho" },
  { value: "left", label: "Izquierdo" },
  { value: "bilateral", label: "Bilateral" },
];

export const patternLabels = {
  rising: "Rising",
  cupping: "Cupping",
  back_pressure: "Back pressure",
  side_pressure: "Side pressure",
  pronation: "Pronacion",
  supination: "Supinacion",
  drag: "Drag",
  high_hook: "Hook alto",
  deep_hook: "Hook profundo",
  containment: "Contencion",
  finish: "Finalizacion",
  squat: "Sentadilla",
  hinge: "Bisagra",
  horizontal_push: "Empuje horizontal",
  vertical_push: "Empuje vertical",
  horizontal_pull: "Tiron horizontal",
  vertical_pull: "Tiron vertical",
  unilateral_leg: "Pierna unilateral",
  trunk_bracing: "Bracing",
  antirotation: "Antirotacion",
  flexor_pronator_isometric: "Flexor-pronador isometrico",
  extensor_balance: "Balance extensor",
  wrist_control: "Control de muneca",
  tendon_tolerance: "Tolerancia tendinosa",
};

export const exerciseDisplayLabels = {
  back_pressure: "Back Pressure",
  dominada_neutra_grip_grueso: "Dominada Neutra con Grip Grueso",
  mesa_hook_contencion_tecnica: "Mesa Hook de Contencion Tecnica",
  pronacion_extendida: "Pronacion Extendida",
  pronacion_media: "Pronacion Media",
  rising_dinamico_correa_pulgar: "Rising Dinamico con Correa al Pulgar",
  rising_isometrico: "Rising Isometrico",
  row_con_straps_y_pecho_apoyado: "Remo con Straps y Pecho Apoyado",
};

export const defaultAthleteProfile = {
  athlete_id: "edgar_garcia",
  display_name: "Edgar Garcia",
  bodyweight_class_target_kg: 80,
  sport: "armwrestling",
  experience_strength_years: 12,
  experience_armwrestling_months_serious: 6,
  primary_goal: "campeon_nacional_80kg_ambos_brazos",
  secondary_goal: "maximizar_fuerza_bruta_transferible",
  constraints: ["escuela", "fatiga_articular_medial_codo"],
  current_strength_profile: {
    back_pressure: "fuerte",
    pronation: "fuerte",
    cupping: "fuerte",
    rising: "debil",
    flexor_pronator_isometric: "debil_secundaria",
    side_pressure: "debil_secundaria",
  },
  priority_distribution: {
    rising: 4,
    flexor_pronator_isometric: 3,
    side_pressure: 2.5,
    back_pressure: 2,
    pronation: 1.5,
    cupping: 1,
  },
  equipment_available: [
    "mesa",
    "correas",
    "banca",
    "sentadilla",
    "remo_con_straps",
  ],
};

const seedCheckin = {
  date: "2026-03-29",
  sleep_hours: 7.5,
  readiness: 8.5,
  bodyweight: 80,
  pain: {
    medial_elbow_right: 2.5,
    lateral_elbow_right: 0,
    shoulder_right: 0,
    wrist_right: 0,
  },
  fatigue: {
    global: 5,
    forearm_hand: 4,
    back: 4,
    legs: 2,
  },
  available_time_min: 110,
  session_type_planned: "specific_aw",
};

const seedSession = {
  session_id: "2026-03-29-specific-aw-01",
  date: "2026-03-29",
  session_type: "specific_aw",
  goal_of_session: "toproll_pesado_evaluacion_real",
  effort_rpe_session: 9.2,
  results: {
    best_pattern: "back_pressure_y_pronacion",
    best_grip_condition: "medio_neutro_grueso",
    main_limitation: "flexor_pronator_isometric",
    could_stop: false,
    could_move: false,
    could_finish: false,
  },
  pain_events: [
    {
      zone: "medial_elbow_right",
      type: "irritability",
      severity: 2.5,
      during: "specific_aw",
      resolved_with: "no_necesario",
    },
  ],
  exercise_entry_count: 12,
};

const seedExerciseEntries = [
  {
    entry_id: "2026-03-29-specific-aw-01-ex-01",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "dominada_neutra_grip_grueso",
    category: "multiarticular",
    pattern: "vertical_pull",
    side: "bilateral",
    load: 30,
    load_unit: "kg",
    effort_type: "dynamic",
    sets: 1,
    reps: 4,
    rpe: 9,
    duration_seconds: 0,
    pain_during: 2,
    vector_quality: 0.88,
    technique_quality: 0.87,
    confirmed_rm: false,
    notes: "top set real; grip grueso; rendimiento alto",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-02",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "dominada_neutra_grip_grueso",
    category: "multiarticular",
    pattern: "vertical_pull",
    side: "bilateral",
    load: 25,
    load_unit: "kg",
    effort_type: "dynamic",
    sets: 1,
    reps: 5,
    rpe: 8,
    duration_seconds: 0,
    pain_during: 2,
    vector_quality: 0.86,
    technique_quality: 0.87,
    confirmed_rm: false,
    notes: "base actual solida de trabajo",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-11",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "dominada_neutra_grip_grueso",
    category: "multiarticular",
    pattern: "vertical_pull",
    side: "bilateral",
    load: 45,
    load_unit: "kg",
    effort_type: "dynamic",
    sets: 1,
    reps: 1,
    rpe: 10,
    duration_seconds: 0,
    pain_during: 2,
    vector_quality: 0.94,
    technique_quality: 0.93,
    confirmed_rm: true,
    notes: "RM confirmado real de dominada pesada",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-03",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "pronacion_media",
    category: "specific_aw",
    pattern: "pronation",
    side: "bilateral",
    load: 40,
    load_unit: "kg",
    effort_type: "dynamic",
    sets: 1,
    reps: 5,
    rpe: 9,
    duration_seconds: 0,
    pain_during: 2,
    vector_quality: 0.9,
    technique_quality: 0.88,
    confirmed_rm: false,
    notes: "top set real de pronacion media",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-04",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "pronacion_media",
    category: "specific_aw",
    pattern: "pronation",
    side: "bilateral",
    load: 35,
    load_unit: "kg",
    effort_type: "dynamic",
    sets: 1,
    reps: 6,
    rpe: 8,
    duration_seconds: 0,
    pain_during: 2,
    vector_quality: 0.87,
    technique_quality: 0.88,
    confirmed_rm: false,
    notes: "RIR 2 registrado como RPE 8",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-05",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "pronacion_extendida",
    category: "specific_aw",
    pattern: "pronation",
    side: "right",
    load: 33,
    load_unit: "kg",
    effort_type: "dynamic",
    sets: 1,
    reps: 10,
    rpe: 8,
    duration_seconds: 0,
    pain_during: 2,
    vector_quality: 0.85,
    technique_quality: 0.86,
    confirmed_rm: false,
    notes: "derecho",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-06",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "pronacion_extendida",
    category: "specific_aw",
    pattern: "pronation",
    side: "left",
    load: 30,
    load_unit: "kg",
    effort_type: "dynamic",
    sets: 1,
    reps: 10,
    rpe: 8.5,
    duration_seconds: 0,
    pain_during: 2,
    vector_quality: 0.82,
    technique_quality: 0.84,
    confirmed_rm: false,
    notes: "izquierdo",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-07",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "rising_isometrico",
    category: "specific_aw",
    pattern: "rising",
    side: "right",
    load: 25,
    load_unit: "kg",
    effort_type: "isometric_hold",
    sets: 1,
    reps: 1,
    rpe: 10,
    duration_seconds: 30,
    pain_during: 2,
    vector_quality: 0.9,
    technique_quality: 0.88,
    confirmed_rm: false,
    notes: "hold al fallo; ultima exposicion del dia cayo a 15 s",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-12",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "rising_isometrico",
    category: "specific_aw",
    pattern: "rising",
    side: "left",
    load: 30,
    load_unit: "kg",
    effort_type: "isometric_hold",
    sets: 1,
    reps: 1,
    rpe: 9.5,
    duration_seconds: 25,
    pain_during: 1,
    vector_quality: 0.88,
    technique_quality: 0.86,
    confirmed_rm: false,
    notes: "izquierdo; primera serie a 30 kg, 25 s maximos, vector correcto",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-08",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "back_pressure",
    category: "specific_aw",
    pattern: "back_pressure",
    side: "right",
    load: 35,
    load_unit: "kg",
    effort_type: "dynamic",
    sets: 1,
    reps: 5,
    rpe: 9,
    duration_seconds: 0,
    pain_during: 2,
    vector_quality: 0.89,
    technique_quality: 0.88,
    confirmed_rm: false,
    notes: "derecho",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-09",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "back_pressure",
    category: "specific_aw",
    pattern: "back_pressure",
    side: "left",
    load: 35,
    load_unit: "kg",
    effort_type: "dynamic",
    sets: 1,
    reps: 3,
    rpe: 9.5,
    duration_seconds: 0,
    pain_during: 2,
    vector_quality: 0.83,
    technique_quality: 0.82,
    confirmed_rm: false,
    notes: "izquierdo",
  },
  {
    entry_id: "2026-03-29-specific-aw-01-ex-10",
    session_id: "2026-03-29-specific-aw-01",
    date: "2026-03-29",
    exercise_name: "back_pressure",
    category: "specific_aw",
    pattern: "back_pressure",
    side: "right",
    load: 30,
    load_unit: "kg",
    effort_type: "dynamic",
    sets: 1,
    reps: 10,
    rpe: 8,
    duration_seconds: 0,
    pain_during: 2,
    vector_quality: 0.87,
    technique_quality: 0.86,
    confirmed_rm: false,
    notes: "derecho; izquierda tambien hizo 30 x 8",
  },
];

export function createSeedData() {
  return {
    version: 7,
    athleteProfile: JSON.parse(JSON.stringify(defaultAthleteProfile)),
    dailyCheckins: [JSON.parse(JSON.stringify(seedCheckin))],
    sessions: [JSON.parse(JSON.stringify(seedSession))],
    exerciseEntries: JSON.parse(JSON.stringify(seedExerciseEntries)),
  };
}
